# Generated by Django 2.1.5 on 2019-01-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passbook',
            old_name='txtype',
            new_name='txType',
        ),
    ]
