# Generated by Django 2.1.5 on 2019-01-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passbook', '0002_auto_20190127_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passbook',
            old_name='passbookOwner',
            new_name='owner',
        ),
    ]
